version: '2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.retention.size=1GB
    volumes:
    - ./prometheus:/etc/prometheus:ro
    depends_on:
    - exporter
    networks:
      back:
        ipv4_address: 172.18.0.4
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana_etc:/etc/grafana
    - grafana_var_lib:/var/lib/grafana
    - ./provisioning:/etc/grafana/provisioning
    depends_on:
    - prometheus
    networks:
      back:
      front:
    restart: always

  exporter:
    container_name: exporter
    build: mining-exporter
    volumes:
    - exporter_data:/prometheus-mining
    network_mode: host
    environment:
      - RIGS="${RIGS}"
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/:ro
    networks:
      back:
        ipv4_address: 172.18.0.5
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    depends_on:
    - prometheus

  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.4.2
    container_name: alertmanager-bot
    networks:
      back:
        ipv4_address: 172.18.0.6
      front:
    restart: always
    environment:
      ALERTMANAGER_URL: http://172.18.0.5:9093
      STORE: bolt
      BOLT_PATH: /data/bot.db
      TEMPLATE_PATHS: /templates/default.tmpl
    volumes:
    - alertmanager-bot_data:/data
    - ./alertmanager-bot.sh:/start.sh
    entrypoint:
    - /start.sh

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.18.0.0/24"
        gateway: 172.18.0.1
  front:
    driver: bridge

volumes:
  grafana_var_lib:
  grafana_etc:
  exporter_data:
  alertmanager-bot_data:  
