version: '2'
services:
  prometheus:
    image: prom/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.retention.size=1GB
    volumes:
    - ./prometheus:/etc/prometheus:ro
    depends_on:
    - exporter
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana_etc:/etc/grafana
    - grafana_var_lib:/var/lib/grafana
    - ./provisioning:/etc/grafana/provisioning
    depends_on:
    - prometheus
    restart: always

  exporter:
    container_name: exporter
    build: mining-exporter
    environment:
    - RIGS=${RIGS}
    restart: always

volumes:
  grafana_var_lib:
  grafana_etc:
