version: '2'
services:
  prometheus:
    image: prom/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.retention.size=1GB
    volumes:
    - ./prometheus:/etc/prometheus:ro
    depends_on:
    - exporter
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana_etc:/etc/grafana
    - grafana_var_lib:/var/lib/grafana
    - ./provisioning:/etc/grafana/provisioning
    depends_on:
    - prometheus
    restart: always

  exporter:
    build: mining-exporter
    volumes:
    - exporter_data:/prometheus-mining
    environment:
      - RIGS=${RIGS}
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/:ro
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    depends_on:
    - prometheus

  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.4.2
    restart: always
    environment:
      ALERTMANAGER_URL: http://alertmanager:9093
      STORE: bolt
      BOLT_PATH: /data/bot.db
      TEMPLATE_PATHS: /templates/default.tmpl
    volumes:
    - alertmanager-bot_data:/data
    - ./alertmanager-bot.sh:/start.sh
    entrypoint:
    - /start.sh

volumes:
  grafana_var_lib:
  grafana_etc:
  exporter_data:
  alertmanager-bot_data:
